#!/usr/bin/env python3
"""
Prometheus Memory — Persona Synthesizer (L2->L3)
Sintetiza cenas L2 em persona L3 + detecta padroes para skills.
Executado semanalmente via cron (segunda 08:00).
"""
import subprocess
import os
import json
import requests as http
from datetime import datetime
from pathlib import Path

PROMETHEUS_USER = os.environ.get("PROMETHEUS_USER", os.environ.get("USER", "user"))
PROMETHEUS_PROJECT = os.environ.get("PROMETHEUS_PROJECT", "default")
LOG_DIR = Path.home() / ".local" / "log"
PERSONA_DIR = Path.home() / ".hermes" / "mnemosyne"
SKILL_GEN_DIR = Path.home() / ".opencode" / "skills" / "generated"

def run_mnemosyne(*args, timeout=30):
    result = subprocess.run(
        ["mnemosyne"] + list(args),
        capture_output=True, text=True, timeout=timeout
    )
    return result.stdout

def get_all_scenes() -> list:
    output = run_mnemosyne("recall", "cena", "50")
    scenes = []
    for line in output.split("\n"):
        if "Content:" in line:
            scenes.append(line.split("Content:")[1].strip())
    return scenes

def synthesize_persona(scenes: list) -> str:
    prompt = f"""Analise as cenas de trabalho abaixo e crie um perfil de persona sintetico em portugues brasileiro.

Cenas recentes (ultimas semanas):
{chr(10).join(f'- {s[:200]}' for s in scenes[-20:])}

Gere um perfil Markdown conciso (max 400 tokens):
## Perfil
- Stack principal, ferramentas preferidas, projetos ativos
- Preferencias (modelos LLM, padroes de trabalho)
- Decisoes importantes recentes (top 5)
- Areas de foco e objetivos
"""
    try:
        from llm_backend import call_llm, available, describe
        if not available():
            print(f"  backend LLM indisponivel ({describe()}) — persona pulada")
            return ""
        return call_llm(prompt, max_tokens=500, temperature=0.3, timeout=45)
    except Exception:
        return ""

def store_persona(persona: str):
    if not persona or persona.startswith("[Erro"):
        print("  Persona NAO persistida (erro na sintese) — evitando contaminar L3")
        return
    ts = datetime.now().strftime("%d/%m/%Y")
    subprocess.run([
        "mnemosyne", "remember",
        f"[{PROMETHEUS_PROJECT}] persona {PROMETHEUS_USER} perfil-sintese semana {ts}: {persona[:800]}",
        "--importance", "0.95",
        "--source", "persona-synthesizer"
    ], capture_output=True, text=True, timeout=15)

    persona_path = PERSONA_DIR / "persona.md"
    PERSONA_DIR.mkdir(parents=True, exist_ok=True)
    persona_path.write_text(f"# Persona — Atualizado {ts}\n\n{persona}")

def generate_skills(scenes: list):
    if not SKILL_GEN_DIR.exists():
        return 0

    prompt = f"""Analise estas cenas de trabalho e detecte padroes recorrentes (3+ ocorrencias).
 Se encontrar padroes, gere skills no formato especificado.
 Se nao encontrar padroes claros, responda exatamente: "NENHUM_PADRAO"

Cenas:
{chr(10).join(f'- {s[:200]}' for s in scenes[-30:])}

Formato de resposta (JSON array, apenas se houver padroes):
[{{"name": "nome-curto", "triggers": ["gatilho1"], "workflow": ["passo1", "passo2"], "tools": ["tool1"], "prompt_addon": "system prompt adicional"}}]
"""
    try:
        from llm_backend import call_llm
        text = call_llm(prompt, max_tokens=800, temperature=0.3, timeout=45)
        if "NENHUM_PADRAO" in text:
            return 0

        json_start = text.find("[")
        json_end = text.rfind("]") + 1
        if json_start == -1:
            return 0
        skills = json.loads(text[json_start:json_end])
        SKILL_GEN_DIR.mkdir(parents=True, exist_ok=True)
        created = 0
        for skill in skills:
            safe_name = skill["name"].lower().replace(" ", "-").replace("/", "-")[:40]
            skill_path = SKILL_GEN_DIR / f"{safe_name}.md"
            if skill_path.exists():
                continue
            content = f"""# skill: {skill['name']}
# auto-generated by Prometheus Memory
# data: {datetime.now().strftime('%Y-%m-%d')}

## Gatilhos
{chr(10).join(f'- "{t}"' for t in skill.get('triggers', []))}

## Fluxo de trabalho
{chr(10).join(f'{i+1}. {s}' for i, s in enumerate(skill.get('workflow', [])))}

## Tools recomendadas
{chr(10).join(f'- {t}' for t in skill.get('tools', []))}

## System prompt addon
{skill.get('prompt_addon', '')}
"""
            skill_path.write_text(content)
            created += 1
        return created
    except Exception as e:
        return 0

if __name__ == "__main__":
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_path = LOG_DIR / "prometheus-persona.log"
    ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    print(f"[{ts}] Persona synthesizer running...")

    scenes = get_all_scenes()
    print(f"  Cenas encontradas: {len(scenes)}")

    events = []
    if len(scenes) >= 3:
        persona = synthesize_persona(scenes)
        if persona:
            store_persona(persona)
            print(f"  Persona sintetizada: {len(persona)} chars")
            events.append(f"persona={len(persona)}chars")
        else:
            print("  Sintese falhou — L3 nao atualizado")
    else:
        print("  Dados insuficientes para persona (min 3 cenas)")

    skills_created = generate_skills(scenes)
    if skills_created > 0:
        print(f"  Skills geradas: {skills_created}")
        events.append(f"skills={skills_created}")

    msg = f"[{ts}] {', '.join(events) if events else 'sem dados suficientes'}"
    with open(log_path, "a") as f:
        f.write(msg + "\n")
    print("Done")
