#!/usr/bin/env python3
"""
Prometheus Memory — Skill Generator
Detecta padroes recorrentes em cenas L2 e gera skills reutilizaveis.
Executado pelo persona_synthesizer.py semanalmente.
Tambem pode ser executado standalone: python3 skill_generator.py
"""
import json
import os
import requests as http
from datetime import datetime
from pathlib import Path

DEEPSEEK_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
SKILL_GEN_DIR = Path.home() / ".opencode" / "skills" / "generated"

def load_existing_skills() -> set:
    names = set()
    if not SKILL_GEN_DIR.exists():
        return names
    for f in SKILL_GEN_DIR.glob("*.md"):
        content = f.read_text()
        for line in content.split("\n"):
            if line.startswith("# skill:"):
                names.add(line.split(":")[1].strip())
    return names

def detect_skill_patterns(scenes: list) -> list:
    if not DEEPSEEK_KEY:
        return []
    existing = load_existing_skills()

    prompt = f"""Analise estas cenas de desenvolvimento e detecte padroes operacionais recorrentes (3+ ocorrencias).
Se encontrar padroes, crie skills. Se nao, responda exatamente: "NENHUM"

Cenas (ultimas semanas):
{chr(10).join(f'- {s[:250]}' for s in scenes[-30:])}

Skills existentes (nao repetir): {', '.join(existing) if existing else 'nenhuma'}

Responda como JSON array:
[{{
  "name": "nome-curto-sem-espacos",
  "triggers": ["frase gatilho 1", "frase gatilho 2"],
  "workflow": ["passo concreto 1", "passo concreto 2", "passo concreto 3"],
  "tools": ["nome_tool_1", "nome_tool_2"],
  "prompt_addon": "System prompt adicional em portugues, 1-3 frases, descrevendo como executar esta skill"
}}]
"""
    try:
        resp = http.post(
            "https://api.deepseek.com/chat/completions",
            headers={"Authorization": f"Bearer {DEEPSEEK_KEY}"},
            json={
                "model": "deepseek-chat",
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 1000,
                "temperature": 0.3
            },
            timeout=60
        )
        text = resp.json()["choices"][0]["message"]["content"]
        if "NENHUM" in text.upper() and "PADRAO" not in text.upper():
            return []

        json_start = text.find("[")
        json_end = text.rfind("]") + 1
        if json_start == -1:
            return []
        return json.loads(text[json_start:json_end])
    except Exception:
        return []

def save_skill(skill: dict) -> Path:
    SKILL_GEN_DIR.mkdir(parents=True, exist_ok=True)
    safe_name = skill["name"].lower().replace(" ", "-").replace("/", "-")[:40]
    skill_path = SKILL_GEN_DIR / f"{safe_name}.md"

    content = f"""# skill: {skill['name']}
# auto-generated by Prometheus Memory
# data: {datetime.now().strftime('%Y-%m-%d')}

## Gatilhos
{chr(10).join(f'- "{t}"' for t in skill.get('triggers', []))}

## Fluxo de trabalho
{chr(10).join(f'{i+1}. {s}' for i, s in enumerate(skill.get('workflow', [])))}

## Tools recomendadas
{chr(10).join(f'- {t}' for t in skill.get('tools', []))}

## System prompt addon
{skill.get('prompt_addon', '')}
"""
    skill_path.write_text(content)
    return skill_path

if __name__ == "__main__":
    import subprocess

    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Skill Generator running...")

    result = subprocess.run(
        ["mnemosyne", "recall", "cena", "50"],
        capture_output=True, text=True, timeout=30
    )
    scenes = []
    for line in result.stdout.split("\n"):
        if "Content:" in line:
            scenes.append(line.split("Content:")[1].strip())

    print(f"  Cenas analisadas: {len(scenes)}")

    if len(scenes) < 5:
        print("  Dados insuficientes (min 5 cenas)")
        exit(0)

    skills = detect_skill_patterns(scenes)
    created = 0
    for skill in skills:
        path = save_skill(skill)
        print(f"  Skill criada: {skill['name']} -> {path}")
        created += 1

    print(f"Done: {created} skills")
